name: sublime_synoptics
channels:
  - plotly
  - conda-forge
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - _py-xgboost-mutex
  - act-atmos
  - affine
  - aiodns
  - aiofiles
  - aiohttp
  - aiohttp-client-cache
  - aiosignal
  - aiosqlite
  - alembic
  - anyio
  - argon2-cffi
  - argon2-cffi-bindings
  - arrow
  - asttokens
  - async-lru
  - async-retriever
  - atk-1.0
  - attrs
  - aws-c-auth
  - aws-c-cal
  - aws-c-common
  - aws-c-compression
  - aws-c-event-stream
  - aws-c-http
  - aws-c-io
  - aws-c-mqtt
  - aws-c-s3
  - aws-c-sdkutils
  - aws-checksums
  - aws-crt-cpp
  - aws-sdk-cpp
  - azure-core-cpp
  - azure-identity-cpp
  - azure-storage-blobs-cpp
  - azure-storage-common-cpp
  - azure-storage-files-datalake-cpp
  - babel
  - backcall
  - backports
  - backports.functools_lru_cache
  - basemap
  - basemap-data
  - beautifulsoup4
  - bleach
  - blosc
  - bokeh
  - branca
  - brotli
  - brotli-bin
  - brotli-python
  - bzip2
  - c-ares
  - ca-certificates
  - cached-property
  - cached_property
  - cads-api-client
  - cairo
  - cartopy
  - cattrs
  - cdo
  - cdsapi
  - certifi
  - cffi
  - cfitsio
  - cftime
  - charset-normalizer
  - chart-studio
  - click
  - click-plugins
  - cligj
  - cloudpickle
  - cmor
  - cmweather
  - colorama
  - colorcet
  - colorlog
  - colorlover
  - comm
  - contourpy
  - crc32c
  - cufflinks-py
  - cycler
  - cytoolz
  - dask
  - dask-core
  - dataclasses
  - datashader
  - debugpy
  - decorator
  - defusedxml
  - deprecated
  - dill
  - distributed
  - donfig
  - eccodes
  - entrypoints
  - esmf
  - et_xmlfile
  - exceptiongroup
  - executing
  - expat
  - fftw
  - findlibs
  - fiona
  - fmt
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - fqdn
  - freeglut
  - freetype
  - freexl
  - fribidi
  - frozenlist
  - fsspec
  - gdal
  - gdk-pixbuf
  - geopandas
  - geopandas-base
  - geos
  - geotiff
  - geoviews
  - geoviews-core
  - gettext
  - gflags
  - giflib
  - glog
  - gmp
  - graphite2
  - graphviz
  - greenlet
  - gsl
  - gtk2
  - gts
  - harfbuzz
  - hdf4
  - hdf5
  - holoviews
  - hvplot
  - icu
  - idna
  - imbalanced-learn
  - importlib-metadata
  - importlib_metadata
  - importlib_resources
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - isoduration
  - itsdangerous
  - jasper
  - jedi
  - jinja2
  - joblib
  - jplephem
  - json-c
  - json5
  - jsonpointer
  - jsonschema
  - jsonschema-specifications
  - jsonschema-with-format-nongpl
  - jupyter
  - jupyter-lsp
  - jupyter_bokeh
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - jupyter_events
  - jupyter_server
  - jupyter_server_fileid
  - jupyter_server_terminals
  - jupyter_server_ydoc
  - jupyter_ydoc
  - jupyterlab
  - jupyterlab_pygments
  - jupyterlab_server
  - jupyterlab_widgets
  - kaleido-core
  - kealib
  - keyutils
  - kiwisolver
  - krb5
  - lazy_loader
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libabseil
  - libaec
  - libarchive
  - libarrow
  - libarrow-acero
  - libarrow-dataset
  - libarrow-substrait
  - libblas
  - libboost-headers
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcblas
  - libcrc32c
  - libcurl
  - libdeflate
  - libedit
  - libev
  - libevent
  - libexpat
  - libffi
  - libgcc
  - libgcc-ng
  - libgd
  - libgdal
  - libgfortran
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libglu
  - libgomp
  - libgoogle-cloud
  - libgoogle-cloud-storage
  - libgrpc
  - libiconv
  - libjpeg-turbo
  - libkml
  - liblapack
  - libllvm14
  - libnetcdf
  - libnghttp2
  - libnl
  - libnsl
  - libnuma
  - libopenblas
  - libparquet
  - libpng
  - libpq
  - libprotobuf
  - libre2-11
  - librsvg
  - librttopo
  - libsodium
  - libspatialindex
  - libspatialite
  - libsqlite
  - libssh2
  - libstdcxx
  - libstdcxx-ng
  - libthrift
  - libtiff
  - libudunits2
  - libutf8proc
  - libuuid
  - libwebp-base
  - libxcb
  - libxcrypt
  - libxgboost
  - libxml2
  - libxslt
  - libzip
  - libzlib
  - linkify-it-py
  - llvmlite
  - locket
  - lxml
  - lz4
  - lz4-c
  - lzo
  - magics
  - magics-python
  - mako
  - mapclassify
  - markdown
  - markdown-it-py
  - markupsafe
  - mathjax
  - matplotlib-base
  - matplotlib-inline
  - matplotlib-scalebar
  - mdit-py-plugins
  - mdurl
  - metpy
  - minizip
  - mistune
  - msgpack-python
  - multidict
  - multipledispatch
  - multiurl
  - munch
  - munkres
  - nbclassic
  - nbclient
  - nbconvert
  - nbconvert-core
  - nbconvert-pandoc
  - nbformat
  - nco
  - ncplot
  - nctoolkit
  - ncurses
  - nest-asyncio
  - netcdf-fortran
  - netcdf4
  - networkx
  - notebook
  - notebook-shim
  - nspr
  - nss
  - numba
  - numcodecs
  - numpy
  - openblas
  - openjpeg
  - openpyxl
  - openssl
  - optuna
  - optuna-integration
  - orc
  - overrides
  - owslib
  - packaging
  - pandas
  - pandoc
  - pandocfilters
  - panel
  - pango
  - param
  - parso
  - partd
  - patsy
  - pcre2
  - pexpect
  - pickleshare
  - pillow
  - pint
  - pint-xarray
  - pip
  - pixman
  - pkgutil-resolve-name
  - platformdirs
  - plotly
  - pooch
  - poppler
  - poppler-data
  - postgresql
  - proj
  - prometheus_client
  - prompt-toolkit
  - prompt_toolkit
  - psutil
  - pthread-stubs
  - ptyprocess
  - pure_eval
  - py-xgboost
  - py3dep
  - pyarrow
  - pyarrow-core
  - pyarrow-hotfix
  - pycares
  - pycparser
  - pyct
  - pygeoogc
  - pygeoutils
  - pygments
  - pymannkendall
  - pynhd
  - pyparsing
  - pyproj
  - pyshp
  - pysocks
  - python
  - python-cufflinks
  - python-dateutil
  - python-fastjsonschema
  - python-graphviz
  - python-json-logger
  - python-kaleido
  - python-tzdata
  - python_abi
  - pytz
  - pyviz_comms
  - pyxlsb
  - pyyaml
  - pyzmq
  - qtconsole-base
  - qtpy
  - rasterio
  - rdma-core
  - re2
  - readline
  - referencing
  - requests
  - requests-cache
  - retrying
  - rfc3339-validator
  - rfc3986-validator
  - rioxarray
  - rpds-py
  - rtree
  - s2n
  - scikit-learn
  - scipy
  - seaborn
  - seaborn-base
  - send2trash
  - setuptools
  - sgp4
  - shapely
  - simplejson
  - six
  - sklearn-compat
  - skyfield
  - snappy
  - sniffio
  - snuggs
  - sortedcontainers
  - soupsieve
  - spdlog
  - sqlalchemy
  - sqlite
  - stack_data
  - statsmodels
  - tblib
  - tempest-remap
  - tenacity
  - terminado
  - threadpoolctl
  - tiledb
  - tinycss2
  - tk
  - tomli
  - toolz
  - tornado
  - tqdm
  - traitlets
  - types-python-dateutil
  - typing-extensions
  - typing_extensions
  - typing_utils
  - tzcode
  - tzdata
  - uc-micro-py
  - ucx
  - udunits2
  - ujson
  - uri-template
  - uriparser
  - url-normalize
  - urllib3
  - wcwidth
  - webcolors
  - webencodings
  - websocket-client
  - wheel
  - widgetsnbextension
  - wrapt
  - xarray
  - xerces-c
  - xgboost
  - xlrd
  - xorg-fixesproto
  - xorg-inputproto
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxfixes
  - xorg-libxi
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xorgproto
  - xorg-xproto
  - xyzservices
  - xz
  - y-py
  - yaml
  - yarl
  - ypy-websocket
  - zarr
  - zeromq
  - zict
  - zipp
  - zlib
  - zstd
  - pip:
      - igra==23.5
      - sublimpy==0.0.1
      - windrose==1.9.2
