name: sublime_synoptics
channels:
  - conda-forge
dependencies:
  - python=3.10
  - geopandas
  - rioxarray
  - metpy
  - cdsapi
  - scikit-learn
  - scipy
  - ca-certificates
  - openssl
  - jupyter
  - notebook
  - certifi
  - plotly 
  - pint-xarray
  - act-atmos
  - nctoolkit
  - cufflinks-py
  - py3dep
  - pynhd
  - statsmodels
  - openpyxl
  - python-kaleido
  - seaborn
  - pyxlsb
  - xlrd
  - basemap
  - graphviz
  - python-graphviz
  - python-cdo
  - zarr
  - xgboost
  - imbalanced-learn
  - pymannkendall
  - matplotlib-scalebar
  - optuna
  - optuna-integration
